
// This file is automatically generated by Firebase Studio.
// Do not edit manually.

// To change this configuration, update your project's configuration in the App
// and then re-run the `RequestFirebaseBackendTool`.

// You can also use the `UpdateFirebaseProjectTool` to update this configuration.
export const firebaseConfig = {
  "apiKey": "YOUR_API_KEY",
  "authDomain": "YOUR_AUTH_DOMAIN",
  "projectId": "YOUR_PROJECT_ID",
  "storageBucket": "YOUR_STORAGE_BUCKET",
  "messagingSenderId": "YOUR_MESSAGING_SENDER_ID",
  "appId": "YOUR_APP_ID",
  "measurementId": "YOUR_MEASUREMENT_ID"
};
